In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: C:\Users\WIN-11\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
a=np.array((1,2,3))
print(a)

[1 2 3]


In [13]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
b=np.array([[[1,2],[3,4],[5,6]]])
print(b)
np.zeros((2,4))
np.ones((2,2))

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]
  [5 6]]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.random.rand(4)

array([0.33720729, 0.06062511, 0.56784243, 0.85741868])